
    let data = [
        {
            "provider_id": 1,
            "provider_name": "The Mens Night Shelter",
            "provider_description": "We provide 3 levels of accommodation support:<br> <br>stage 1: dormitory style accommodation which including shower and laundry facilities ($10 a night)<br>stage 2: hostel room accommodation ($80 a week)<br>stage 3: community support (tempoary emergency shelter)<br><br>Dormitory services include a bed for the night, shower facilities, clothes washed, cup of tea. Occasionally some light food is donated and made available.<br><br>Facilities: Bathroom, Laundry & Food.",
            "lat": -41.30061,
            "long": 174.77408,
            "hours": "Open: 7 days a week, all year round. Check in: 5:30pm – 9:00pm. Check out: 6:00am – 7:30am",
            "update_message": "fully functional",
            "address": "304 Taranki St, Mt. Cook, Wellington 6011",
            "email": "menshelter@hotmail.com",
            "website_url": "http://wellingtonnightshelter.org.nz/",
            "provider_updated_at": "2018-12-07 01:17:22",
            "service_id": null,
            "service_name": null,
            "units": null,
            "qty_default": null,
            "qty_remaining": null,
            "service_updated_at": null,
            "service_type_id": null,
            "service_type_name": null,
            "service_type_code": null,
            "icon": null
        },
        {
            "provider_id": 2,
            "provider_name": "Compassion Soup Kitchen",
            "provider_description": "Breakfast is free, dinner costs $2 each night, or guests can buy a five or ten trip meal ticket. We believe the $2 charge supports the dignity of guests by involving choice and purchase rather than charity, and it encourages people to think about budgeting and how they prioritise spending their money.<br>In the mornings we serve hot soup and bread. The evening meals are ‘family style’ meals – for example, roast pork and vegetables, chicken and pasta, stews and vegetables. We usually serve dessert three nights per week and fresh fruit whenever it is available. Our kitchen staff works hard to ensure that the meals have a high nutritional value as we are aware that many of our guests rely on the food service here to meet their daily recommended intake across all food groups.<br>Every day is different – sometimes we serve up to 100 people in an evening and 60 for breakfast. Other days can be  quieter and numbers can go up and down for no obvious reason. Some people have been coming for long periods and others pass through. When someone stops coming we often don’t know the reasons. Catering for the fluctuating number of guests is one of the challenges for the kitchen staff – but we never run out of food!",
            "lat": -41.30071,
            "long": 174.77418,
            "hours": "Open: Monday-Friday 9am-4pm",
            "update_message": "fully functional",
            "address": "132 Tory St, TeAro, Wellington 6011",
            "email": "compassionsoupkitchen@hotmail.com",
            "website_url": "https://soupkitchen.org.nz/about-us/",
            "provider_updated_at": "2018-12-07 01:17:22",
            "service_id": null,
            "service_name": null,
            "units": null,
            "qty_default": null,
            "qty_remaining": null,
            "service_updated_at": null,
            "service_type_id": null,
            "service_type_name": null,
            "service_type_code": null,
            "icon": null
        },
        {
            "provider_id": 3,
            "provider_name": "Wellington City Mission",
            "provider_description": " What to bring!! <br><br>If you are working:<br>An ATM receipt or bank statement<br>Your latest payslip<br>If you are receiving a Work and Income benefit/student allowance:<br>An ATM receipt or bank statement<br>A breakdown of your benefit or statement letter from Studylink<br>A printout of your Work and Income entitlements or a decline letter<br>If you have no income:<br>An ATM receipt or bank statement<br>A benefit stop or stand down letter/your final payslip<br>You are able to request these Work and Income documents over the counter at any of their offices.",
            "lat": -41.30081,
            "long": 174.77428,
            "hours": "Open: Monday to Thursday 10.00am to 3.00pm and Fridays 10.30am to 3.00pm",
            "update_message": "fully functional",
            "address": "19 Gordon Place, Newtown, Wellington",
            "email": "wellingtoncitymission@hotmail.com",
            "website_url": "https://www.wellingtoncitymission.org.nz/struggling-to-put-food-on-the-table/",
            "provider_updated_at": "2018-12-07 01:17:22",
            "service_id": null,
            "service_name": null,
            "units": null,
            "qty_default": null,
            "qty_remaining": null,
            "service_updated_at": null,
            "service_type_id": null,
            "service_type_name": null,
            "service_type_code": null,
            "icon": null
        },
        {
            "provider_id": 4,
            "provider_name": "St Vincient De Paul Wellington",
            "provider_description": "WHAT SHOULD I BRING WHEN ACCESSING A FOOD PARCEL?<br>A form of photo I.D.<br>Decline letter from Work and Income showing that no food grant is available and a breakdown of the Work and Income benefit received.<br>Income details.<br>A bank statement with your last transactions.<br>If applicable, a copy of your budgeting sheet prepared by a qualified budgeter.<br>If you do not have any of the above documents, come in anyway and chat to our team to discuss other options.",
            "lat": -41.30091,
            "long": 174.77438,
            "hours": "Open: Monday-Friday 9am-4pm",
            "update_message": "fully functional",
            "address": "Level 1, 207 Riddiford Street, Newtown, Wellington 6021",
            "email": "vinniesWellington@hotmail.com",
            "website_url": "https://www.vinnies-wellington.org.nz/food-bank/",
            "provider_updated_at": "2018-12-07 01:17:22",
            "service_id": null,
            "service_name": null,
            "units": null,
            "qty_default": null,
            "qty_remaining": null,
            "service_updated_at": null,
            "service_type_id": null,
            "service_type_name": null,
            "service_type_code": null,
            "icon": null
        },
        {
            "provider_id": 5,
            "provider_name": "The Salvation Army",
            "provider_description": "Please bring suitable I.D amd proof of address.",
            "lat": -41.30101,
            "long": 174.77448,
            "hours": "Open: Monday-Friday 9am-5pm",
            "update_message": "fully functional",
            "address": "204 Cuba Street, Te Aro, Wellington 6011",
            "email": "salvationArmy@hotmail.com",
            "website_url": "https://www.salvationarmy.org.nz/help-us/food-banks",
            "provider_updated_at": "2018-12-07 01:17:22",
            "service_id": null,
            "service_name": null,
            "units": null,
            "qty_default": null,
            "qty_remaining": null,
            "service_updated_at": null,
            "service_type_id": null,
            "service_type_name": null,
            "service_type_code": null,
            "icon": null
        },
        {
            "provider_id": 6,
            "provider_name": "DCM",
            "provider_description": "DCM has adopted the byline “together we can end homelessness in Wellington” which reflects our current focus on the needs of one key marginalised group – people experiencing homelessness, or who are at risk of homelessness, supporting them on a journey towards sustainable housing and wellbeing.  Over the past decade we have supported literally hundreds of people to successfully exit homelessness and sustain housing.<br>The most marginalised people in our city come to us because they genuinely feel welcome and because what we do works and makes a difference in their lives. ",
            "lat": -41.30111,
            "long": 174.77458,
            "hours": "9am-4pm",
            "update_message": "fully functional",
            "address": "2 Lukes Lane, Te Aro, Wellington",
            "email": "DCM@hotmail.com",
            "website_url": "https://www.dcm.org.nz/contact/",
            "provider_updated_at": "2018-12-07 01:17:22",
            "service_id": null,
            "service_name": null,
            "units": null,
            "qty_default": null,
            "qty_remaining": null,
            "service_updated_at": null,
            "service_type_id": null,
            "service_type_name": null,
            "service_type_code": null,
            "icon": null
        },
        {
            "provider_id": 7,
            "provider_name": "Wesley Methodist Church",
            "provider_description": "Showers available from 9am–5pm, Monday–Friday",
            "lat": -41.30121,
            "long": 174.77468,
            "hours": "Monday-Friday, 9am-5pm",
            "update_message": "fully functional",
            "address": "75 Taranki Street, Te Aro, Wellington 6011",
            "email": "wesleymethodistchurch@hotmail.com",
            "website_url": "http://www.wesleychurch.org.nz/index.php/about-us",
            "provider_updated_at": "2018-12-07 01:17:22",
            "service_id": null,
            "service_name": null,
            "units": null,
            "qty_default": null,
            "qty_remaining": null,
            "service_updated_at": null,
            "service_type_id": null,
            "service_type_name": null,
            "service_type_code": null,
            "icon": null
        },
        {
            "provider_id": 8,
            "provider_name": "Catacombs",
            "provider_description": "Catacombs is a drop in centre for inner city Wellington residents, including homeless and people in transit, providing a place for people to socialise and keep warm. There is a TV lounge, phone for local calls, shower and laundry facilities.",
            "lat": -41.30131,
            "long": 174.77478,
            "hours": "Open: 7–10pm, Monday–Friday, 2.30–10pm, Saturday, 11am–10pm, Sunday",
            "update_message": "fully functional",
            "address": "Level 1, 131 Manners Street, Te Aro, Wellington 6011",
            "email": "Catacombs@hotmail.com",
            "website_url": "https://www.facebook.com/pg/Catacombs-Incorporated-226736744022280/about/",
            "provider_updated_at": "2018-12-07 01:17:22",
            "service_id": null,
            "service_name": null,
            "units": null,
            "qty_default": null,
            "qty_remaining": null,
            "service_updated_at": null,
            "service_type_id": null,
            "service_type_name": null,
            "service_type_code": null,
            "icon": null
        },
        {
            "provider_id": 9,
            "provider_name": "Evolve",
            "provider_description": "Free healthcare and social support for people aged 10–25 years.<br>Includes medical service, counselling, advocacy, alcohol and drug<br>support, accommodation and employment assistance, youth work,<br>groups, activities and events.",
            "lat": -41.30141,
            "long": 174.77488,
            "hours": "Open: Monday–Friday 10am -6pm",
            "update_message": "fully functional",
            "address": "Level 2 James Smith Building, Corner Cuba and Manners streets, Te Aro",
            "email": "Evolve@hotmail.com",
            "website_url": "https://evolveyouth.org.nz/contact-us/",
            "provider_updated_at": "2018-12-07 01:17:22",
            "service_id": null,
            "service_name": null,
            "units": null,
            "qty_default": null,
            "qty_remaining": null,
            "service_updated_at": null,
            "service_type_id": null,
            "service_type_name": null,
            "service_type_code": null,
            "icon": null
        }
    ]


export default data